add github actions
eclipse/jetty.docker pull request #31
Opened 2020-11-10 02:09 UTC by olamy

2020-11-10 09:36 UTC, joakime requested changes

2020-11-10 09:36 UTC, joakime commented on Jenkinsfile
> +    sh "mvn -V -B -DfailIfNoTests=false -fae $cmdline"
perhaps we should make the 2 CI builds equivalent?

Have both be ..

```
mvn -V -B -e -DfailIfNoTests=false -fae clean verify
```

2020-11-10 09:36 UTC, joakime commented on .github/dependabot.yml
> +updates:
There's also a docker ecosystem here.

Consider adding ...
```
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
```

We might need to tweak this `directory` setting later.

2020-11-17 08:19 UTC, lachlan-roberts commented
@olamy this is failing the tests
> dependabot.yml Failing after 1s — Your .github/dependabot.yml contained invalid details

Maybe remove Travis CI in this PR? Although it does seem to be passing now.

2020-11-17 08:36 UTC, lachlan-roberts commented
I guess we're scrapping the use of that `hack-my-builds.sh` script from the docker guys then. The GithubCI is just doing the same test as we do on the Jenkins build.

It looks like the docker-library images have moved to using GithubCI as well, maybe we could do something similar to what they do there.  https://github.com/docker-library/openjdk/blob/master/.github/workflows/ci.yml

2020-11-23 22:54 UTC, lachlan-roberts commented
@olamy this is failing eca check, I don't think you signed latest commit

2020-11-23 23:30 UTC, olamy commented
@lachlan-roberts  arghh I did that using merge option from GH UI bad idea :) I will fix that

2020-11-24 00:38 UTC, merged